"""empty message

Revision ID: 7ddbfaab3e8c
Revises: d3a9ecb106f3
Create Date: 2023-06-20 21:37:11.599506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ddbfaab3e8c'
down_revision = 'd3a9ecb106f3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
